name: Build Electron App
on:
  push:
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > math-homework.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v4
        with:
          name: homework_pre
          path: math-homework.txt

  build-and-release:
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: homework_pre

      - name: Display structure of downloaded files
        shell: bash
        run: ls -R
