name: Upload to Google Drive
on:
  push:
    branches: [main]

# on:
#   release:
#     types: [published]

jobs:
  download-and-uploading:

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Get Build Workflow Run Id
        shell: bash
        run: |
          RUNID=$(gh run list --repo rezafikkri/test-build-electron-vite --json databaseId --workflow=build.yml --limit 1 | jq '.[0].databaseId')
          echo "RUNID=$RUNID" >> $GITHUB_ENV

      - uses: actions/download-artifact@v4
        with:
          github_token: ${{ env.GITHUB_TOKEN }}
          name: upload_to_google_drive
          run-id: ${{ env.RUNID }}

      - name: Display structure of downloaded files
        run: ls -R
