name: Upload to Google Drive
on:
  release:
    types: [published]

jobs:
  download-and-uploading:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PARENT_FOLDER_ID: 1jn2NjBBRHY0cR4xrd9pLjUUFr5QjScEv
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Get Build Workflow Run Id
        shell: bash
        run: |
          RUNID=$(gh run list --repo rezafikkri/test-build-electron-vite --json databaseId --workflow=build.yml --limit 1 | jq '.[0].databaseId')
          echo "RUNID=$RUNID" >> $GITHUB_ENV

      - name: Create Release Dir
        shell: bash
        run: mkdir release

      - uses: actions/download-artifact@v4
        with:
          github-token: ${{ env.GITHUB_TOKEN }}
          name: upload_to_google_drive
          run-id: ${{ env.RUNID }}
          path: release

      - name: Display structure of downloaded files
        run: ls -R

      - name: Get App Version
        shell: bash
        run: echo "APP_VERSION=$(jq '.version' package.json)" >> $GITHUB_ENV

      - name: Upload Windows Artifacts TO Google Drive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v2.2.2
        with:
          target: |
            release/squirrel.windows/x64/RELEASES
            release/squirrel.windows/x64/test-build-electron-vite-1.10.0 Setup.exe
            release/squirrel.windows/x64/test_build_electron_vite-1.10.0-full.nupkg
          credentials: ${{ secrets.G_SERVICE_CREDENTIAL }}
          parent_folder_id: ${{ env.PARENT_FOLDER_ID }}
          child_folder: ${{ env.APP_VERSION }}/windows
          override: true
          owner: fikkri.reza@gmail.com

      - name: Upload Linux Artifacts TO Google Drive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v2.2.2
        with:
          target: release/deb/x64/test-build-electron-vite_1.10.0_amd64.deb
          credentials: ${{ secrets.G_SERVICE_CREDENTIAL }}
          parent_folder_id: ${{ env.PARENT_FOLDER_ID }}
          child_folder: ${{ env.APP_VERSION }}/Linux
          override: true
          owner: fikkri.reza@gmail.com

